apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-backend
  namespace: sonarqube

spec:
  entryPoints:
    - websecure

  routes:
  - match: "Host(`sonarqube.drakkar.link`)"
    kind: Rule
    services:
    - name: sonarqube-sonarqube
      port: 9000

  tls:
    secretName: sonarqube-certificate
