---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    name: gitlab-runner
  type: NodePort